name: Nasa Update Manifest Stage CI

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  actions: read
  checks: write

jobs:
  check-tag-on-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Verify tag is on main
        run: |
          git fetch origin main
          if ! git merge-base --is-ancestor ${{ github.sha }} origin/main; then
            echo "::error::Tag must point to a commit on main branch"
            exit 1
          fi

  nasa-ci:
    needs: check-tag-on-main
    uses: NationalLibraryOfNorway/nasa-workflows/.github/workflows/update-manifest-stage.yaml@main
    secrets:
      VAULT_URL: ${{ secrets.NB_VAULT_URL }} 
      VAULT_SECRET_PATH: ${{ secrets.NASA_VAULT_SECRET_PATH }}
      VAULT_ROLE: ${{ secrets.NASA_VAULT_ROLE }}
      VAULT_ROLE_ID: ${{ secrets.NASA_VAULT_ROLE_ID }}
      VAULT_SECRET_ID: ${{ secrets.NASA_VAULT_SECRET_ID }}